import{a as L,S as b,i as f}from"./assets/vendor-DXaqCXe3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const v="49372428-d1d84138fa434fefe0cc10176",w="https://pixabay.com/api/";async function y(r,t=1,s=15){const n={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s};try{return(await L.get(w,{params:n})).data}catch(e){throw console.error("Помилка запиту:",e),e}}const m=document.querySelector(".gallery"),S=new b(".gallery a",{captionDelay:250});function g(r){const t=r.map(s=>`  
                <li class="gallery-item">  
                    <a class="gallery-link" href="${s.largeImageURL}">  
                        <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}"/>  
                        <ul class="content-list">  
                            <li class="content-item"><p>Likes</p><p>${s.likes}</p></li>  
                            <li class="content-item"><p>Views</p><p>${s.views}</p></li>  
                            <li class="content-item"><p>Comments</p><p>${s.comments}</p></li>  
                            <li class="content-item"><p>Downloads</p><p>${s.downloads}</p></li>  
                        </ul>  
                    </a>  
                </li>  
            `).join("");m.innerHTML="",m.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){m.innerHTML=""}const h=document.querySelector(".form"),c=document.querySelector(".loader"),i=document.querySelector(".load-more");let l="",a=1;const d=15;let p=0;h.addEventListener("submit",$);i.addEventListener("click",M);async function $(r){if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),l!==""){a=1,q(),c.classList.remove("hidden"),i.classList.add("hidden");try{const t=await y(l,a,d);if(p=t.totalHits,t.hits.length===0){f.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),d*a<p&&i.classList.remove("hidden")}catch(t){console.log("Помилка отримання даних:",t)}finally{c.classList.add("hidden"),h.reset()}}}async function M(){a+=1,i.classList.add("hidden"),c.classList.remove("hidden");try{const r=await y(l,a,d);g(r.hits),d*a<p?i.classList.remove("hidden"):f.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(r){console.log(r)}finally{c.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
