import{a as L,S as w,i as p}from"./assets/vendor-DXaqCXe3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const b="49372428-d1d84138fa434fefe0cc10176",v="https://pixabay.com/api/";async function f(r,t=1,o=15){const a={key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:o};try{return(await L.get(v,{params:a})).data}catch(e){throw console.error("Помилка запиту:",e),e}}const g=document.querySelector(".gallery"),S=new w(".gallery a",{captionDelay:250});function y(r){const t=r.map(o=>`  
                <li class="gallery-item">  
                    <a class="gallery-link" href="${o.largeImageURL}">  
                        <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"/>  
                        <ul class="content-list">  
                            <li class="content-item"><p>Likes</p><p>${o.likes}</p></li>  
                            <li class="content-item"><p>Views</p><p>${o.views}</p></li>  
                            <li class="content-item"><p>Comments</p><p>${o.comments}</p></li>  
                            <li class="content-item"><p>Downloads</p><p>${o.downloads}</p></li>  
                        </ul>  
                    </a>  
                </li>  
            `).join("");g.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){g.innerHTML=""}const h=document.querySelector(".form"),l=document.querySelector(".loader"),n=document.querySelector(".load-more");let c="",i=1;const d=15;let m=0;h.addEventListener("submit",P);n.addEventListener("click",$);async function P(r){if(r.preventDefault(),c=r.target.elements["search-text"].value.trim(),c!==""){i=1,q(),l.classList.remove("hidden"),n.classList.add("hidden");try{const t=await f(c,i,d);if(m=t.totalHits,t.hits.length===0){p.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),d*i<m&&n.classList.remove("hidden")}catch(t){console.log("Помилка отримання даних:",t)}finally{l.classList.add("hidden"),h.reset()}}}async function $(){i+=1,n.classList.add("hidden"),l.classList.remove("hidden");try{const r=await f(c,i,d);y(r.hits),O(),d*i<m?n.classList.remove("hidden"):p.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(r){console.log(r)}finally{l.classList.add("hidden")}}function O(){const r=document.querySelector(".gallery-item");if(r){const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
